### ISSUE TITLE
Propagation output: Change units from sec -> au, au/day to day -> au, au/day

### ISSUE THREAD

**Issue by PerezHz** [PerezHz/PlanetaryEphemeris.jl#19]
Related to PerezHz/NEOs.jl#17. I would propose to make this change here; it can actually save us the unit conversion step after propagation here, and then users can always use `auday2kmsec` and related functions to change ephemeris units if needed. What do you think, @lbenet, @LuEdRaMo?

**Comment by LuEdRaMo** [comment]
I'm in favor of this change; as you mention, it can save us a conversion here and the `loadeph` function at `NEOs.jl`. Should we address this before https://github.com/PerezHz/PlanetaryEphemeris.jl/issues/20?.

**Comment by PerezHz** [comment]
This change should be easier to pursue than fixing #20, so yes I'd propose to first tackle the issue here.

**Comment by PerezHz** [comment]
Fixed by #22
